 library(XML)
 library(RJSONIO)
 library(RCurl)
 u = "https://www.city-data.com/city/California.html"
 ll = readLines(u)
 grep("Acton", ll)
 grep("Acton", ll, value = TRUE)
 doc = htmlParse(ll)
 ll[2170:2175]
 tbls = readHTMLTable(doc)
 length(tbls)
 sapply(tbls, nrow)
 tbls = getNodeSet(doc, "//table")
 length(tbls)
 saveXML(doc, "ca.html")
 sapply(tbls, xmlAttrs)
 tbl = getNodeSet(doc, "//table[@id = 'cityTab']")
 length(tbl)
 tbl = getNodeSet(doc, "//table[@id = 'cityTAB']")
 length(tbl)
 ca = readHTMLTable(tbl[[1]])
 head(ca)
 dim(ca)
 ll2 = readLines("https://www.city-data.com/")
 grep("New Jersey", ll2, value = TRUE)
 doc2 = htmlParse(ll2)
 length(getNodeSet(doc2, "//table[ contains(., 'New Jersey')]"))
 length(getNodeSet(doc2, "//table"))
 length(getNodeSet(doc2, "//a[contains(., 'New Jersey')]"))
 nj = getNodeSet(doc2, "//a[contains(., 'New Jersey')]")
 nj[[1]]
 nj[[2]]
 nj = getNodeSet(doc2, "//a[contains(., 'New Jersey')]/..")
 nj[[1]]
 xmlName(xmlParent(nj[[1]]))
 xmlAttrs(xmlParent(nj[[1]]))
 xmlAttrs(xmlParent(nj[[2]]))
 xmlName(xmlParent(xmlParent(nj[[2]])))
 xmlAttrs(xmlParent(xmlParent(nj[[2]])))
 xmlAttrs(xmlParent(xmlParent(nj[[1]])))
 length(getNodeSet(doc2, "//a[@class  = 'cities_list']"))
 length(getNodeSet(doc2, "//a[@class  = 'cities_list']/@href"))
 getNodeSet(doc2, "//a[@class  = 'cities_list']/@href")
 cu = unlist(getNodeSet(doc2, "//a[@class  = 'cities_list']/@href"))
 table(duplicated(cu))
 cu2 = unique(cu)
 cu2
 ll3  = lapply(cu2, readLines)
 cu = unlist(getNodeSet(doc2, "//a[@class  = 'cities_list']/@href"))
 cu = unlist(getNodeSet(doc2, "//a[@class  = 'cities_list']"))
 cu[[1]]
 xmlValue(cu[[1]])
 sapply(cu, xmlGetAttr, "href")
 cu3 = structure(sapply(cu, xmlGetAttr, "href"), names = sapply(cu, xmlValue))
 unique(cu3)
 cu3
 docs = lapply(ll3, htmlParse)
 sapply(docs, function(doc)  length(getNodeSet(doc, "//table[@id = 'cityTAB']")))
 tbls2 = lapply(docs[-length(docs)], function(doc) readHTMLTable(getNodeSet(doc, "//table[@id = 'cityTAB']")[[1]]))
 sapply(tbls2, nrow)
 head(tbls2[[2]])
 head(tbls2[[5]])
 getNodeSet(docs[[5]], "//table[@id = 'cityTAB']//a")
 doc = htmlParse(readLines("https://www.city-data.com/city/Yuba-Foothills-California.html"))
 getNodeSet(doc, "//text()[contains(., 'median household income')]")
 getNodeSet(doc, "//text()[contains(., 'median household income')]/..")
 getNodeSet(doc, "//text()[contains(., 'median household income')]/../..")
 length(getNodeSet(doc, "//section[@id]"))
 sapply(getNodeSet(doc, "//section[@id]"), xmlGetAttr, "id")
 getNodeSet(doc, "//text()[contains(., 'median household income')]/../..")
 getNodeSet(doc, "//text()[contains(., 'median household income')]/../..")[[1]]
 saveXML(getNodeSet(doc, "//text()[contains(., 'median household income')]/../..")[[1]])
 
